apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  DB_URL: "jdbc:postgresql://$(aws rds describe-db-instances --db-instance-identifier inventory-service-db --region eu-west-1 --query 'DBInstances[0].Endpoint.Address' --output text):5432/inventory"
  DB_USER: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"

